### ISSUE TITLE
Issue on download - 2010 census

### ISSUE THREAD

**Issue by fernandanevesw** [datazoompuc/datazoom_social_Stata#74]
Hi, 

I just downloaded the 2010 census microdata for a research project I would like to develop from IBGE's website ([here](https://www.ibge.gov.br/estatisticas/sociais/populacao/9662-censo-demografico-2010.html?=&t=microdados)), but I have the following error when using the 'db datazoom_censo' command in Stata/MP 17.0

> Arquivo Amostra_Pessoas_14munic.txt não encontrado
> Ver http://www.ibge.gov.br/home/estatistica/populacao/censo2010/resultados_gerais_amostra_areas_ponderacao/default_redefinidos.shtm

I get the above message after I submit my query using the dialog box. I followed your instructions in [this video](https://www.youtube.com/watch?v=9Vc5SX1ZpBM&ab_channel=DataZoom) and [this video](https://www.youtube.com/watch?v=VHiqyngl71A&ab_channel=DataZoom) on YouTube.

Can you point me in the right direction?

Many thanks!

### (recebido via email)

**Comment by FlaviaCDAndrade** [comment]
Same problem as Fernanda. Does anyone have this file? It is no longer on the IBGE website.

**Comment by FranciscoCavalcanti** [comment]
Hi @FlaviaCDAndrade 

In order to use all the data from the 2010 census and solve the STATA error message you received, you need to download the microdata for each state in Brazil and also the data file for the 14 municipalities with the areas redefined through the following link: [Microdados para os 14 municípios com as áreas redefinidas](https://ftp.ibge.gov.br/Censos/Censo_Demgrafico_2010/Resultados_Gerais_da_Amostra_areas_de_ponderacao/Municipios_com_areas_de_ponderacao_refinadas/microdados_%2014_municipios_com_areas_refinas_20160331.zip).

Hope this helps and if you need any further assistance, please don't hesitate to get in touch.
